### PR TITLE
Issue#719: Updated var to const/let

### PR DESCRIPTION
**Pull request by ael-mas**
Updated var declarations to use const or let instead.
Added strict mode to file.

### CODE REVIEW

**Comment by humphd** [comment]
@ael-mas how is this coming?  Any update?

**Comment by humphd** [comment]
@ael-mas did you want this PR closed in favour of the new one you opened?

**Comment by ael-mas** [comment]
The new one should have the correct variable declarations using const instead of let. Apologies if I didn't modify my original changes properly on github.

**Comment by humphd** [comment]
OK, no problem.  Closing in favour of #741.  In future, you can just make more commits and push to your same branch, and it will add to/update an existing PR vs. making a new one.

**Pull request closed without merging**
