### PR TITLE
Fix issue #766: Remove describe.only from shim tests

### PR DESCRIPTION
**Pull request by bcheidemann**

### CODE REVIEW

**Comment by bcheidemann** [comment]
Resolves issue: https://github.com/filerjs/filer/issues/766

@humphd

**Comment by humphd** [comment]
I fixed CI on master to avoid this random build failure. Can you rebase this so it runs through to completion?

**Comment by bcheidemann** [comment]
> I fixed CI on master to avoid this random build failure. Can you rebase this so it runs through to completion?

Done =)

**Review by humphd — CHANGES_REQUESTED** [review]
Can you revert the changes to `package-lock.json` and `tests/spec/filer.spec.js`, which aren't necessary for this fix?  In general we don't want to include unrelated changes in commits.

```
git checkout master tests/spec/filer.spec.js
git checkout master package-lock.json
...etc
```

The rest looks great.

**Comment by bcheidemann** [comment]
> Can you revert the changes to `package-lock.json` and `tests/spec/filer.spec.js`, which aren't necessary for this fix?  In general we don't want to include unrelated changes in commits.
> 
> 
> 
> ```
> 
> git checkout master tests/spec/filer.spec.js
> 
> git checkout master package-lock.json
> 
> ...etc
> 
> ```
> 
> 
> 
> The rest looks great.

No problem 👍

**Comment by bcheidemann** [comment]
I've made the requested changes

**Review by humphd — APPROVED** [review]
Excellent, thank you!

**Pull request merged**
