### PR TITLE
Add tests to fsPromises.lstat()---issue-514

### PR DESCRIPTION
**Pull request by qwang135**
As what I wrote in the title, I've added a test for fsPromises.lstat().

### CODE REVIEW

**Comment by jrkong** [comment]
Could you explain why you deleted fs.close.spec? Your latest tests are failing because you're missing the fs.close.spec test file.

**Comment by SeanPrashad** [comment]
Just to add onto @jrkong's question, if this was a mistake, you can erase your commits by running `git reset --hard HEAD~1` if you want to *permanently* delete the last commit you made.

**Comment by zdong11** [comment]
I think you are missing the fs.close.spec test file. You can add fs.close.spec and try again

**Comment by humphd** [comment]
I've fixed this up, rebased, and landed in https://github.com/filerjs/filer/commit/9a7d3514d831c7cc1c5e980649c578641ed16b59.

**Pull request closed without merging**
