### PR TITLE
add test for fs.open with wx flag for existing file

### LINKED ISSUE #623: Add test for fs.open() with O_WRITE + O_EXCLUSIVE and existing file
https://codecov.io/gh/filerjs/filer/src/master/src/filesystem/implementation.js#L594 is a branch we don't test.  To hit it, I think we need:

* add a test to `fs.open.spec.js`
* `mkdir` a directory `/tmp` then create a file in the directory, `/tmp/file`
* now try to `fs.open()` that path and use the `'wx'` flag
* expect an `ENOENT` error to be returned

Somewhat similar to the structure of [this test](https://github.com/filerjs/filer/blob/master/tests/spec/fs.open.spec.js#L50).

### PR DESCRIPTION
**Pull request by cdrani**
Fixes #623

### CODE REVIEW

**Comment by cdrani** [comment]
Sure, no problem.

**Comment by cdrani** [comment]
The test is failing, expecting 'EEXIST' to equal 'ENOENT'.

**Comment by humphd** [comment]
You can just run `npm test` and it will rebuild automatically.  Did you change your test file to expect `EEXIST` after making that change to the implementation?

Also, can you push your changes up again and I'll review again, and help fix anything.

**Comment by cdrani** [comment]
Yes, I made all the changes. Will push now.

**Comment by cdrani** [comment]
Concerning this
>  No binary for FirefoxHeadless browser on your platform.
  Please, set "FIREFOX_BIN" env variable.

I noticed that I have ChromeHeadless, but not FirefoxHeadless. How are these setup? Why do I have one binary and not the other?

**Comment by humphd** [comment]
@cdrani do you have Firefox installed on your machine?  That should be enough to make this work.

At any rate, this looks great, nice work.  I'm going to merge.

**Comment by cdrani** [comment]
Oh, I use the developer version. That might be the issue. Thanks for the help!

**Pull request merged**
