### PR TITLE
first  commid

### PR DESCRIPTION
**Pull request by zdong11**
Try "R" (read) to replace "R+" (read and write) is valid.

### CODE REVIEW

**Comment by zdong11** [comment]
Wow, maybe I was wrong. It seems that this method is not recognized, and may involve errors in "grammar". When we write code, we must follow the grammar rules.

**Comment by SeanPrashad** [comment]
Hey @zdong11 - did you need some help getting this off the ground?

**Comment by zdong11** [comment]
yes, please. I need help . :)

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: Sean <notifications@github.com>
发送时间: 星期四, 九月 27, 2018 5:09 下午
收件人: filerjs/filer
抄送: Zhibo Dong; Mention
主题: Re: [filerjs/filer] first commid (#531)


Hey @zdong11<https://github.com/zdong11> - did you need some help getting this off the ground?

―

**Comment by SeanPrashad** [comment]
Sure! We should do a couple of things:

**Comment by zdong11** [comment]
Thank you for your help, this is very important to me.

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: Sean <notifications@github.com>
发送时间: 星期四, 九月 27, 2018 5:26 下午
收件人: filerjs/filer
抄送: Zhibo Dong; Mention
主题: Re: [filerjs/filer] first commid (#531)


Sure! We should do a few things first:

  1.  Update the title of this pull request to be something more descriptive - for example, Fixes #512 - Add a test to do Y where XXX is the issue number that you're trying to fix and Y is a description of the actual fix!

  2.  We can remove those 6 old commits by running: git checkout issue512 && git reset --hard HEAD~5 && git push -f - Note: This will permanently remove those commits, if you don't want to do so, then don't run it!

  3.  The unit tests for fs.open can be found within /tests/spec/fs.open.spec.js - I saw in the issue #512<https://github.com/filerjs/filer/issues/512> that you wanted to test the difference between r and r+ (documentation found here<https://github.com/filerjs/filer#fsopenpath-flags-mode-callback>). I was thinking we could test r+ on a file that is read-only - what do you think?

―

**Comment by SeanPrashad** [comment]
No worries - this should get you going and if you get stuck again, reach out to everyone in Slack at https://seneca-open-source.slack.com/ 👍

**Comment by yevseytsev** [comment]
If test for "r" was working, then for "r+" it should working also, because "r+" comparing to "r" has no limitations

**Comment by humphd** [comment]
@zdong11 it looks like you ran into some problems with this.  Did you want to close this pull request, and submit a new one with only your test for `r` vs. `r+`?  If you want to fix this one and restore the file you removed, that's fine too.  But if you're stuck and not sure how, just go ahead and redo it.

Let us know if you need help, either here, in Slack, or in class.

**Comment by humphd** [comment]
I'm going to close this, as it looks like there's been no progress.  If that's wrong, let me know and we can continue either here or in a new PR.

**Pull request closed without merging**
