### PR TITLE
Fix #387: Add unit test for opening and writing to a file using the Promise API

### LINKED ISSUE #387: Testing open, close and stat using the promise based API
```javascript
const fs = new Filer.FileSystem().promises;
fs.open('/myfile', 'w+')
  .then(fd => fs.close(fd))
  .then(() => fs.stat('/myfile'))
  .then(stats => { console.log(`stats: ${JSON.stringify(stats)}`); })
  .catch(err => { console.error(err); })
```
I'd like to write a test for the above example in the readme file. The test would check if the file was opened, closed, and whether the expected file information was returned.

### PR DESCRIPTION
**Pull request by dnguneratne**
This pull request adds a new test to ensure that,
- a file was opened,
- a buffer of 8 numbers were successfully written to it,
- and check if the file is of type `FILE`,

using the Promise API.

### CODE REVIEW

**Comment by SeanPrashad** [comment]
Hey @dnguneratne - nice work 🎉 🎉

I have one suggestion that would help move this along faster - it looks like you need to rebase as @0xazure's commit was landed recently.

I think `git checkout master && git pull upstream master && git checkout issue-387 && git rebase master` would be what we're looking for.

**Comment by dnguneratne** [comment]
I forked this repo today and branched off master. So if I'm not mistaken it should include @0xazure's commit. However, I know that the develop branch is behind. I'm not sure if this PR should be to develop or master, especially because of #388. @humphd?

**Comment by 0xazure** [comment]
Per #383 it looks like PRs should target `master`, though #388 brings up a great point about how pre-built versions of Filer are distributed from GitHub; @humphd should we be re-building `dist/` and including those changes (if any) in future PRs?

**Comment by humphd** [comment]
We haven't had a good automated release story for what's in `dist/` and what's on `npm`.  That needs to happen.  For the moment, there's going to be a ton of churn on `master` over the coming few weeks as we land tests and other student PRs, so I'm not too worried about things being out of sync.  When you run `npm test` it will rebuild, so it will always be fresh.

Finally, a word about `develop` vs. `master`.  I recently switched the default branch of Filer to `master` from `develop` so as to not confuse new git users.  However, it may have messed up some people who might have been on `develop`.

I'm not going to stress too much about rebasing in this first release for all students; if you know how to do it, and are comfortable, go for it.  But if not, we'll just merge and deal with rebasing later.

**Comment by humphd** [comment]
Filed https://github.com/filerjs/filer/issues/404 to figure out `dist/`

**Comment by humphd** [comment]
To fix this PR, do the following (assuming `filerjs/filer` is your `upstream` remote):

```
$ git fetch upstream
$ git checkout -B master upstream/master
$ git checkout issue-387
$ git rebase master
...assuming this works without issue...
$ git push origin issue-387 -f
```

If that doesn't work (I haven't tested it), let me know and I'll help debug.

**Pull request closed without merging**
